[[2023.1]]
day = 10
amount = 100
name = "Kupars"

[[2022.12]]
day = 5
amount = 100
name = "Kupars"

[[2022.11]]
day = 6
amount = 10
name = "Kupars"

[[2022.11]]
day = 5
amount = 100
name = "Kupars"

[[2026.5]]
day = 5
amount = 100
name = "Kupars"

[[2026.8]]
day = 5
amount = 100
name = "Kupars"
