[[2025.7]]
day = 5
amount = 3500
name = "Eldvindr"

[[2025.7]]
day = 3
amount = 100
name = "Siaospeed"

[[2025.7]]
day = 3
amount = 1
name = "Debonair53"

[[2024.5]]
day = 26
amount = 1743
name = "zeropolicy4017"

[[2024.3]]
day = 8
amount = 1000
name = "星晨"

[[2024.2]]
day = 13
amount = 1000
name = "星晨"

[[2024.2]]
day = 13
amount = 700
name = "jiapuludeng"

[[2024.2]]
day = 11
amount = 10000
name = "无刻"

[[2024.2]]
day = 10
amount = 1500
name = "jiapuludeng"

[[2024.1]]
day = 25
amount = 1
name = "MRmaozi2440"

[[2024.1]]
day = 19
amount = 5000
name = "CaoPeiSheng446"

[[2023.10]]
day = 21
amount = 20000
name = "OvO17Wink"

[[2023.10]]
day = 21
amount = 15000
name = "Kupars"

[[2023.10]]
day = 3
amount = 10
name = "Siaospeed"

[[2023.8]]
day = 3
amount = 6600
name = "Nevevolpe"

[[2023.7]]
day = 29
amount = 500
name = "蛋神教教主"

[[2023.5]]
day = 20
amount = 1000
name = "jiapuludeng"

[[2023.5]]
day = 13
amount = 1000
name = "mcxiaohao"

[[2023.5]]
day = 5
amount = 1000
name = "mcxiaohao"

[[2023.4]]
day = 25
amount = 1000
name = "mcxiaohao"

[[2023.4]]
day = 24
amount = 1000
name = "mcxiaohao"

[[2023.4]]
day = 22
amount = 1000
name = "Suejdow31"

[[2023.4]]
day = 21
amount = 1000
name = "mcxiaohao"

[[2023.4]]
day = 15
amount = 1000
name = "mcxiaohao"

[[2023.4]]
day = 5
amount = 1500
name = "mcxiaohao"

[[2023.3]]
day = 28
amount = 500
name = "mcxiaohao"

[[2023.3]]
day = 28
amount = 1
name = "*飷"

[[2023.3]]
day = 12
amount = 10000
name = "Nevevolpe"

[[2023.1]]
day = 26
amount = 10000
name = "laok233"

[[2023.1]]
day = 21
amount = 1145
name = "jiapuludeng"

[[2023.1]]
day = 21
amount = 1145
name = "KNwither3599"

[[2023.1]]
day = 15
amount = 1145
name = "KNwither3599"

[[2023.1]]
day = 12
amount = 100
name = "Siaospeed"

[[2022.11]]
day = 28
amount = 600
name = "l*e"

[[2022.11]]
day = 27
amount = 500
name = "X*i"

[[2022.11]]
day = 27
amount = 1000
name = "jiapuludeng"

[[2022.11]]
day = 27
amount = 700
name = "GloatingDaisy33"

[[2022.11]]
day = 27
amount = 45
name = "chen雪杨"

[[2022.11]]
day = 27
amount = 1614
name = "KNwither3599"

[[2022.11]]
day = 24
amount = 1451
name = "ZhuShu1225"


