[[2023.1]]
day = 10
amount = 114514
name = "Kupars"

[[2022.12]]
day = 5
amount = 9
name = "Kupars"

[[2022.11]]
day = 6
amount = 16
name = "Kupars"

[[2022.11]]
day = 5
amount = 5100
name = "Kupars"

[[2026.5]]
day = 5
amount = 483
name = "Kupars"

[[2026.8]]
day = 5
amount = 181981
name = "Kupars"
