name: Deploy
on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: pnpm/action-setup@v4
      name: Install pnpm
      with:
        version: latest
        run_install: false
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'pnpm'
    - name: Install dependencies
      run: pnpm install
    - name: Build Site
      run: pnpm run docs:build
    - name: Deploy
      env:
        RSYNC_PWD: ${{ secrets.RSYNC_PASSWORD }}
      run: |
        echo $RSYNC_PWD > rsync.pwd
        sudo chmod 600 rsync.pwd
        rsync  --port=30004 -av --delete docs/.vuepress/dist/ githubactions@lib.kupars.top::owlLibrary --password-file=rsync.pwd          

